window.AXEN_PRODUCTS = [
  {
    id: "oversize-core",
    slug: "axen-oversize-incrivel",
    name: "AXEN Oversize Incrível",
    category: "Oversize",
    audience: ["masculino", "lifestyle", "sale"],
    price: 149.9,
    oldPrice: 199.9,
    front: "../assets/produtos/oversize-frente.png",
    back: "../assets/produtos/incrivel-costas.png",
    spin: "../assets/produtos/incrivel-360.gif",
    sizes: ["P", "M", "G", "GG", "GGG"],
    description: "Oversize premium com frente minimalista, costas impactantes e identidade AXEN."
  },
  {
    id: "oversize-jesus",
    slug: "axen-oversize-jesus-is-king",
    name: "AXEN Oversize Jesus Is King",
    category: "Oversize",
    audience: ["masculino", "lifestyle"],
    price: 149.9,
    oldPrice: 199.9,
    front: "../assets/produtos/oversize-frente.png",
    back: "../assets/produtos/jesus-costas.png",
    sizes: ["P", "M", "G", "GG", "GGG"],
    description: "Modelagem ampla com presença visual marcante e conforto premium."
  },
  {
    id: "oversize-bulking",
    slug: "axen-oversize-bulking-season",
    name: "AXEN Oversize Bulking Season",
    category: "Oversize",
    audience: ["masculino", "lifestyle"],
    price: 149.9,
    oldPrice: 199.9,
    front: "../assets/produtos/oversize-frente.png",
    back: "../assets/produtos/bulking-costas.png",
    sizes: ["P", "M", "G", "GG", "GGG"],
    description: "Gramatura premium para quem transforma consistência em evolução."
  },
  {
    id: "oversize-legday",
    slug: "axen-oversize-legday",
    name: "AXEN Oversize Legday",
    category: "Oversize",
    audience: ["masculino"],
    price: 149.9,
    oldPrice: 199.9,
    front: "../assets/produtos/oversize-frente.png",
    back: "../assets/produtos/legday-costas.png",
    sizes: ["P", "M", "G", "GG"],
    description: "Caimento solto e liberdade total para os treinos mais intensos."
  },
  {
    id: "oversize-arnold",
    slug: "axen-oversize-arnold-edition",
    name: "AXEN Oversize Arnold Edition",
    category: "Oversize",
    audience: ["masculino", "lifestyle", "sale"],
    price: 99.9,
    oldPrice: 149.9,
    front: "../assets/produtos/oversize-frente.png",
    back: "../assets/produtos/arnold-costas.png",
    sizes: ["P", "M", "G", "GG"],
    description: "Edição inspirada na era clássica do bodybuilding."
  },
  {
    id: "oversize-energy",
    slug: "axen-oversize-energy",
    name: "AXEN Oversize Energy",
    category: "Oversize",
    audience: ["masculino", "lifestyle"],
    price: 149.9,
    oldPrice: 199.9,
    front: "../assets/produtos/oversize-frente.png",
    back: "../assets/produtos/energy-costas.png",
    sizes: ["P", "M", "G", "GG", "GGG"],
    description: "Assinatura elétrica AXEN nas costas e frente minimalista."
  },
  {
    id: "cropped-athlete",
    slug: "cropped-axen-athlete",
    name: "Cropped AXEN Athlete",
    category: "Croppeds",
    audience: ["feminino", "sale"],
    price: 129.9,
    oldPrice: 169.9,
    front: "../assets/produtos/oversize-frente.png",
    back: "../assets/produtos/incrivel-costas.png",
    sizes: ["PP", "P", "M", "G"],
    colors: ["Preto", "Grafite"],
    description: "Corte esportivo e estética minimalista para treino e lifestyle."
  },
  {
    id: "legging-force",
    slug: "legging-axen-force",
    name: "Legging AXEN Force",
    category: "Leggings",
    audience: ["feminino"],
    price: 199.9,
    oldPrice: 249.9,
    front: "../assets/produtos/oversize-frente.png",
    back: "../assets/produtos/energy-costas.png",
    sizes: ["PP", "P", "M", "G", "GG"],
    colors: ["Preto", "Grafite"],
    description: "Compressão equilibrada, cintura alta e acabamento fosco premium."
  },
  {
    id: "cap-signature",
    slug: "bone-axen-signature",
    name: "Boné AXEN Signature",
    category: "Acessórios",
    audience: ["acessorios", "lifestyle"],
    price: 99.9,
    oldPrice: 129.9,
    front: "../assets/produtos/oversize-frente.png",
    back: "../assets/produtos/jesus-costas.png",
    sizes: ["Único"],
    colors: ["Preto"],
    description: "Acessório minimalista com ajuste preciso para a rotina urbana."
  }
];
